export const testResults = `{
    "executionTime": 62,
    "results": [
        {
            "titles": [
                {
                    "id": "CONSTEXT000050388934",
                    "cid": "CONSTEXT000050388934",
                    "title": "Décision 2024-160 ORGA - 15 octobre 2024 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL,   Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l’ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] <mark>Conseil</mark> constitutionnel en date du 15 octobre 2024,   DÉCIDE :   Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2024 - octobre 2025 : Mmes Karin [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2427733s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000049184160",
                    "cid": "CONSTEXT000049184160",
                    "title": "Décision 2024-158 ORGA - 08 février 2024 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ;  Vu l’ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] ALEXIS et Audrey CHAFFARD, conseillères référendaires à la Cour des comptes, sont nommées rapporteures adjointes auprès du <mark>Conseil</mark> constitutionnel en remplacement de M.  [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2404042s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000048175495",
                    "cid": "CONSTEXT000048175495",
                    "title": "Décision 2023-157 ORGA - 05 octobre 2023 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l’ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...]  ; Vu la lettre du vice-président du <mark>Conseil</mark> d’État en date du 31 août 2023; Vu la lettre du premier président de la Cour des comptes en date du 3 octobre 2023 ; En application de la délibération du <mark>Conseil</mark> [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2326911s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000049631353",
                    "cid": "CONSTEXT000049631353",
                    "title": "Décision 2024-159 ORGA - 28 mai 2024 - Décision portant création du comité d’histoire du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] Article 2. - Le comité d’histoire du <mark>Conseil</mark> constitutionnel est présidé par le Président du <mark>Conseil</mark> constitutionnel. [...] . - Le comité d’histoire du <mark>Conseil</mark> constitutionnel se réunit au moins trois fois par an. Son secrétariat est assuré par le secrétariat général du <mark>Conseil</mark> constitutionnel. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2414472s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000046778529",
                    "cid": "CONSTEXT000046778529",
                    "title": "Décision 2022-156 ORGA - 24 novembre 2022 - Nomination d'un rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] . - Monsieur David GUILBAUD, conseiller référendaire à la Cour des comptes, est nommé rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel pour la période de novembre 2022 à octobre 2023. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2233767s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000046488658",
                    "cid": "CONSTEXT000046488658",
                    "title": "Décision 2022-155 ORGA - 13 octobre 2022 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] <mark>Conseil</mark> constitutionnel en date du 13 octobre 2022, D É C I DE : Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2022 - octobre 2023 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2229548s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000046216466",
                    "cid": "CONSTEXT000046216466",
                    "title": "Décision 2022-154 ORGA - 04 août 2022 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] ORGA du 17 février 2022 portant nomination d'un rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel ; Vu la lettre du vice-président du <mark>Conseil</mark> d'État en date du 18 juillet 2022 ; En application de la [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2223446s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000045802098",
                    "cid": "CONSTEXT000045802098",
                    "title": "Décision 2022-153 ORGA - 12 mai 2022 - Nomination d'un rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] au <mark>Conseil</mark> d'État, est nommée rapporteure adjointe auprès du <mark>Conseil</mark> constitutionnel, en remplacement de Madame Cécile BARROIS de SARIGNY. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2214342s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000045243096",
                    "cid": "CONSTEXT000045243096",
                    "title": "Décision 2022-151 ORGA - 17 février 2022 - Nomination d'un rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] requêtes au <mark>Conseil</mark> d'État, est nommé rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel, en remplacement de Madame Sophie ROUSSEL. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2205761s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000044239152",
                    "cid": "CONSTEXT000044239152",
                    "title": "Décision 2021-149 ORGA - 14 octobre 2021 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] <mark>Conseil</mark> constitutionnel en date du 14 octobre 2021, D É C I D E : Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2021 - octobre 2022 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2131153s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000042524731",
                    "cid": "CONSTEXT000042524731",
                    "title": "Décision 2020-148 ORGA - 14 octobre 2020 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 14 octobre 2020, DÉCIDE : Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2020 - octobre 2021 : Madame Émilie [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2027697s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000039351742",
                    "cid": "CONSTEXT000039351742",
                    "title": "Décision 2019-145 ORGA - 07 novembre 2019 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 7 novembre 2019, DÉCIDE : Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2019 - octobre 2020 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1932219s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000039250229",
                    "cid": "CONSTEXT000039250229",
                    "title": "Décision 2019-144 ORGA - 25 juillet 2019 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] des requêtes au <mark>Conseil</mark> d'État, sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période de juillet 2019 à octobre 2019. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1926329s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000033105021",
                    "cid": "CONSTEXT000033105021",
                    "title": "Décision 2016-263 L - 16 juin 2016 - Nature juridique des dispositions relatives au <mark>conseil</mark> national de l'éducation populaire et de la jeunesse et au <mark>conseil</mark> national de la jeunesse  - Réglementaire",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] général du <mark>Conseil</mark> constitutionnel sous le n° 2016-263 L. [...] Sa composition et les modalités de désignation de ses membres relèvent d'un décret en <mark>Conseil</mark> d'État. [...]",
            "type": "_doc",
            "nature": "l",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1616809s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000037554727",
                    "cid": "CONSTEXT000037554727",
                    "title": "Décision 2018-143 ORGA - 25 octobre 2018 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 25 octobre 2018, D É C I D E : Article 1er. - Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2018-octobre 2019 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1829419s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000037148495",
                    "cid": "CONSTEXT000037148495",
                    "title": "Décision 2018-142 ORGA - 29 juin 2018 - Nomination d'un rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] BOKDAM-TOGNETTI, maître des requêtes au <mark>Conseil</mark> d'État, est nommée rapporteur adjoint auprès du <mark>Conseil</mark> constitutionnel pour la période de juillet 2018 à septembre 2018. [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1818217s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000021852259",
                    "cid": "CONSTEXT000021852259",
                    "title": "Décision 2010-603 DC - 11 février 2010 - Loi organisant la concomitance des renouvellements des <mark>conseils</mark> généraux et des <mark>conseils</mark> régionaux  - Conformité",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] des <mark>conseils</mark> régionaux, le 2 février 2010, par M. [...] Considérant que les députés et sénateurs requérants défèrent au <mark>Conseil</mark> constitutionnel la loi organisant la concomitance des renouvellements des <mark>conseils</mark> généraux et des <mark>conseils</mark> régionaux ; qu'ils contestent [...]",
            "type": "_doc",
            "nature": "dc",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscl1004224s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000048175496",
                    "cid": "CONSTEXT000048175496",
                    "title": "Décision 2023-31 ELEC - 29 septembre 2023 - Observations du <mark>Conseil</mark> constitutionnel relatives aux élections législatives des 12 et 19 juin 2022",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] Le <mark>Conseil</mark> constitutionnel a procédé à l’audition des parties dans onze affaires. [...] S’agissant de la faculté, pour le <mark>Conseil</mark> constitutionnel, de ne pas prononcer d’inéligibilité, elle a été mise en œuvre à 82 reprises, soit parce que le <mark>Conseil</mark> constitutionnel a estimé que le candidat [...]",
            "type": "_doc",
            "nature": "elec",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2326234s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000036157849",
                    "cid": "CONSTEXT000036157849",
                    "title": "Décision 2017-141 ORGA - 19 octobre 2017 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] <mark>Conseil</mark> constitutionnel en date du 19 octobre 2017, D É C I D E : Article 1er.- Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2017-octobre 2018 : Madame Aurélie [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscl1729634s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000045972836",
                    "cid": "CONSTEXT000045972836",
                    "title": "Décision 2022-198 PDR - 16 juin 2022 - Observations du <mark>Conseil</mark> constitutionnel sur l'élection présidentielle des 10 et 24 avril 2022",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] Le <mark>Conseil</mark> a écarté une telle argumentation en jugeant que « Le décret du 26 janvier 2022 ayant été délibéré en <mark>conseil</mark> des ministres, il devait être signé, comme il l'a été, par le Président de la République [...] Dans l'ensemble, les rapports des délégués du <mark>Conseil</mark> constitutionnel, ainsi que l'examen des divers procès-verbaux adressés au <mark>Conseil</mark> ou dont il a eu connaissance, révèlent le bon fonctionnement des [...]",
            "type": "_doc",
            "nature": "pdr",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2217867s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000033387479",
                    "cid": "CONSTEXT000033387479",
                    "title": "Décision 2016-136 ORGA - 10 novembre 2016 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 10 novembre 2016, D É C I D E : Article 1er.- Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2016-octobre 2017 : Monsieur [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1632904s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000041749145",
                    "cid": "CONSTEXT000041749145",
                    "title": "Décision 2019-830 QPC - 12 mars 2020 - <mark>Conseil</mark> national des centres commerciaux [Délivrance des autorisations d'exploitation commerciale] - Conformité",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE <mark>CONSEIL</mark> CONSTITUTIONNEL A ÉTÉ SAISI le 13 décembre 2019 par le <mark>Conseil</mark> d'État (décision n° 431724 du même jour), dans les conditions prévues à l'article 61-1 de la Constitution, d'une question prioritaire [...] Cette question a été posée pour l'association <mark>Conseil</mark> national des centres commerciaux par la SCP Piwnica et Molinié, avocat au <mark>Conseil</mark> d'État et à la Cour de cassation. [...]",
            "type": "_doc",
            "nature": "qpc",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2007452s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000031494381",
                    "cid": "CONSTEXT000031494381",
                    "title": "Décision 2015-134 ORGA - 12 novembre 2015 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 12 novembre 2015, D É C I D E : Article 1er.- Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2015-octobre 2016 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1528759s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000029641913",
                    "cid": "CONSTEXT000029641913",
                    "title": "Décision 2014-131 ORGA - 23 octobre 2014 - Nomination de rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] LE PRÉSIDENT DU <mark>CONSEIL</mark> CONSTITUTIONNEL, Vu la Constitution du 4 octobre 1958, notamment son titre VII ; Vu l'ordonnance n° 58-1067 du 7 novembre 1958 modifiée portant loi organique sur le <mark>Conseil</mark> constitutionnel [...] du <mark>Conseil</mark> constitutionnel en date du 23 octobre 2014, D É C I D E : Article 1er.- Sont nommés rapporteurs adjoints auprès du <mark>Conseil</mark> constitutionnel pour la période octobre 2014-octobre 2015 : Mesdames [...]",
            "type": "_doc",
            "nature": "orga",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx1425396s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        },
        {
            "titles": [
                {
                    "id": "CONSTEXT000045972837",
                    "cid": "CONSTEXT000045972837",
                    "title": "Décision 2022-298 L - 02 juin 2022 - Nature juridique de diverses dispositions relatives au <mark>Conseil</mark> général de l'environnement et du développement durable  - Réglementaire",
                    "legalStatus": null,
                    "startDate": null,
                    "endDate": null,
                    "nature": null
                }
            ],
            "text": "[...] général du <mark>Conseil</mark> constitutionnel sous le n° 2022-298 L. [...] par le vice-président du <mark>Conseil</mark> général de l'environnement et du développement durable » figurant au 4° de l'article L. 751-6 du code de commerce et des mots « du <mark>Conseil</mark> général de l'environnement et [...]",
            "type": "_doc",
            "nature": "l",
            "origin": "CONSTIT",
            "etat": null,
            "date": null,
            "sections": [],
            "num": null,
            "jorfText": null,
            "numParution": null,
            "datePublication": null,
            "dossiersLegislatifs": [],
            "nor": "cscx2216324s",
            "motsCles": [],
            "appellations": [],
            "idAttachment": null,
            "sizeAttachment": null,
            "moreArticle": false,
            "additionalResult": {},
            "raisonSociale": null,
            "idcc": null,
            "descriptionFusionHtml": null,
            "dateSignature": null,
            "dateDiffusion": null,
            "reference": null,
            "themes": [],
            "conforme": false,
            "resumePrincipal": [],
            "autreResume": []
        }
    ],
    "facets": [
        {
            "facetElem": "SOLUTION_ELECT",
            "field": "solution",
            "values": {
                "Annulation": 75,
                "Annulation - Inéligibilité": 17,
                "Annulation - Non lieu à statuer [QPC]": 2,
                "Approbation du compte": 4,
                "Approbation du compte - réformation": 20,
                "Enquête": 6,
                "Inéligibilité": 2093,
                "Inéligibilité - rejet [QPC]": 1,
                "Irrecevabilité": 8,
                "Non lieu à prononcer l'inéligibilité": 291,
                "Non lieu à statuer": 49,
                "Rectification d'erreur matérielle": 9,
                "Rejet": 1784,
                "Rejet - Conformité [QPC]": 2,
                "Rejet - non lieu à statuer [QPC]": 4,
                "Rejet - rejet de la QPC": 1,
                "Rejet du compte": 2,
                "Rejet du recours": 1,
                "Réformation": 1
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "SOLUTION_AUTRE",
            "field": "solution",
            "values": {
                "Compatibilité": 15,
                "Conditions réunies": 1,
                "Déchéance": 17,
                "Décision abrogée": 2,
                "Décision avant dire droit": 1,
                "Incompatibilité": 18,
                "Inéligibilité - Démission d'office": 1,
                "Irrecevabilité": 3,
                "Non lieu à statuer": 8,
                "Rejet": 4,
                "Sursis à statuer": 1
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "SOLUTION_CONSTIT",
            "field": "solution",
            "values": {
                "Compétence de l'État": 1,
                "Compétence de l'État - non lieu à statuer": 1,
                "Compétence de l'état": 2,
                "Compétence de la collectivité": 6,
                "Conformité": 929,
                "Conformité - déclassement organique": 10,
                "Conformité - non lieu à statuer": 13,
                "Conformité - réserve": 137,
                "Conformité - réserve - déclassement organique": 4,
                "Conformité - réserve - non lieu à statuer": 4,
                "Domaine législatif": 3,
                "Domaine réglementaire": 8,
                "Décision avant dire droit": 1,
                "Incompétence pour statuer": 4,
                "Irrecevabilité": 5,
                "Législatif": 13,
                "Non conformité": 5,
                "Non conformité de date à date": 2,
                "Non conformité de date à date - non lieu à statuer": 1,
                "Non conformité de date à date - réserve": 1,
                "Non conformité partielle": 366,
                "Non conformité partielle - déclassement organique": 2,
                "Non conformité partielle - effet différé": 19,
                "Non conformité partielle - effet différé - non lieu à statuer": 1,
                "Non conformité partielle - effet différé - réserve": 6,
                "Non conformité partielle - effet différé - réserve - non lieu à statuer": 1,
                "Non conformité partielle - effet différé - réserve transitoire": 2,
                "Non conformité partielle - réserve": 60,
                "Non conformité partielle - réserve - déclassement organique": 13,
                "Non conformité totale": 151,
                "Non conformité totale - effet différé": 69,
                "Non conformité totale - effet différé - non lieu à statuer": 1,
                "Non conformité totale - effet différé - réserve transitoire": 30,
                "Non conformité totale - effet différé - réserve transitoire - non lieu à statuer": 1,
                "Non conformité totale - non lieu à statuer": 1,
                "Non lieu à statuer": 34,
                "Non méconnaissance de la loi organique": 3,
                "Partiellement compétence de la collectivité": 5,
                "Partiellement réglementaire": 61,
                "Partiellement réglementaire - non lieu à statuer": 1,
                "Rectification d'erreur matérielle": 3,
                "Rejet": 15,
                "Réglementaire": 224,
                "Réglementaire - non lieu à statuer": 1
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "NATURE_CONSTIT",
            "field": "natureQualifiee",
            "values": {
                "Compétences outre-mer (LOM)": 15,
                "Dispositions promulguées (QPC)": 999,
                "Loi du pays (LP)": 8,
                "Loi ordinaire (DC)": 590,
                "Loi organique (DC)": 180,
                "Referendum d'initiative partagée (RIP)": 8,
                "Règlements des Assemblées (DC)": 87,
                "Traité (DC)": 14
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "NATURE_NORME_AUTRE",
            "field": "natureQualifiee",
            "values": {
                "Délégalisation (L)": 307,
                "Fin de non recevoir (FNR)": 14
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "NATURE_ELCT",
            "field": "natureQualifiee",
            "values": {
                "Autres décisions du contentieux électoral": 38,
                "Election du Président de la République": 197,
                "Election du Sénat": 304,
                "Election à l’Assemblée Nationale": 3932,
                "Référendum": 38
            },
            "childs": {},
            "totalElement": 0
        },
        {
            "facetElem": "NATURE_AUTRE",
            "field": "natureQualifiee",
            "values": {
                "Avis sur circonstances exceptionnelles": 1,
                "Déchéance parlementaire": 27,
                "Décision d’organisation interne": 160,
                "Incompatibilité": 40,
                "Obligations fiscales": 1
            },
            "childs": {},
            "totalElement": 0
        }
    ],
    "totalResultNumber": 6962,
    "totalArticleResultNumber": 0,
    "typePagination": "DEFAUT",
    "descriptionFusionHtml": null
}`